language: php
sudo: false
services:
  - docker
php:
  - 8.5
  - nightly
before_install:
  - pecl install -f redis <<< ''
before_script:
  - docker run -d -p 6379:6379 --name redis-modules redislabs/redismod:latest
  - composer install -n
script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - export XDEBUG_MODE=coverage
  - vendor/bin/codecept run unit --coverage --coverage-xml
