language: php
sudo: false
services:
  - docker
php:
  - 8.0
  - 8.1
  - nightly
before_install:
  - pecl install -f redis <<< ''
before_script:
  - docker run -d -p 6379:6379 --name redis-modules redislabs/redismod:latest
  - composer install -n
script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - export XDEBUG_MODE=coverage
  - vendor/bin/codecept run unit --coverage --coverage-xml
after_script:
  - if [ $TRAVIS_PHP_VERSION = '8.1' ]; then php vendor/bin/php-coveralls; fi
after_success:
  - travis_retry php vendor/bin/php-coveralls -v
  - vendor/bin/test-reporter